[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "KompasAPI-stubs-generator"
version = "0.0.2"
dependencies = [
  "pywin32",
  "bs4",
  "lxml"
]
requires-python = ">=3.11"
authors = [
  {name = "Nikita Mamay", email = "nikitamamay@mail.ru"},
]
maintainers = [
  {name = "Nikita Mamay", email = "nikitamamay@mail.ru"},
]
description = "Программа для создания stub-файлов для Python-модулей API САПР «Компас-3D»."
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]
keywords = ["cad", "kompas3d", "kompas-3d"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
  "Operating System :: Microsoft :: Windows",
  "Intended Audience :: Developers",
  "Topic :: Scientific/Engineering",
]

[project.urls]
Repository = "https://github.com/nikitamamay/KompasAPI-stubs-generator"
